edition = "2021"
version = "One"
unstable_features = true

max_width = 120
newline_style = "Unix"

brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = true
empty_item_single_line = false
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Item"
imports_layout = "Vertical"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 20
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
