[package]
name = "bfbfe"
version = "0.2.0"
authors = ["Reperak"]
edition = "2021"
description = "All-in-one Brainfuck parser, optimizer, transpiler, and interpreter"
license = "GPL-3.0-or-later"

[dependencies]
