[target.'cfg(all())']
rustflags = [
    "-Dclippy::self_named_module_files",
    "-Dclippy::undocumented_unsafe_blocks",
    "-Wclippy::arithmetic_side_effects",
    "-Wclippy::as_ptr_cast_mut",
    "-Wclippy::bool_to_int_with_if",
    "-Wclippy::borrow_as_ptr",
    "-Wclippy::branches_sharing_code",
    "-Wclippy::case_sensitive_file_extension_comparisons",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::cloned_instead_of_copied",
    "-Wclippy::copy_iterator",
    "-Wclippy::create_dir",
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::decimal_literal_representation",
    "-Wclippy::default_trait_access",
    "-Wclippy::default_union_representation",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::derive_partial_eq_without_eq",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_line_after_outer_attr",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::enum_glob_use",
    "-Wclippy::equatable_if_let",
    "-Wclippy::exit",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::explicit_deref_methods",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::explicit_iter_loop",
    "-Wclippy::fallible_impl_from",
    "-Wclippy::filetype_is_file",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::format_push_string",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::get_unwrap",
    "-Wclippy::if_not_else",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::implicit_clone",
    "-Wclippy::imprecise_flops",
    "-Wclippy::inconsistent_struct_constructor",
    "-Wclippy::index_refutable_slice",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::items_after_statements",
    "-Wclippy::iter_on_empty_collections",
    "-Wclippy::iter_on_single_items",
    "-Wclippy::iter_with_drain",
    "-Wclippy::large_digit_groups",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_clamp",
    "-Wclippy::manual_instant_elapsed",
    "-Wclippy::manual_let_else",
    "-Wclippy::manual_ok_or",
    "-Wclippy::manual_string_new",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_bool",
    "-Wclippy::match_on_vec_items",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wild_err_arm",
    "-Wclippy::mem_forget",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::mut_mut",
    "-Wclippy::mutex_atomic",
    "-Wclippy::mutex_integer",
    "-Wclippy::needless_bitwise_bool",
    "-Wclippy::needless_collect",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_pass_by_value",
    "-Wclippy::negative_feature_names",
    "-Wclippy::non_ascii_literal",
    "-Wclippy::nonstandard_macro_braces",
    "-Wclippy::option_if_let_else",
    "-Wclippy::panic_in_result_fn",
    "-Wclippy::pub_use",
    "-Wclippy::range_minus_one",
    "-Wclippy::range_plus_one",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::redundant_closure_for_method_calls",
    "-Wclippy::redundant_else",
    "-Wclippy::redundant_feature_names",
    "-Wclippy::redundant_pub_crate",
    "-Wclippy::ref_binding_to_reference",
    "-Wclippy::ref_option_ref",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_name_method",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::significant_drop_in_scrutinee",
    "-Wclippy::similar_names",
    "-Wclippy::stable_sort_primitive",
    "-Wclippy::str_to_string",
    "-Wclippy::string_to_string",
    "-Wclippy::suboptimal_flops",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::transmute_ptr_to_ptr",
    "-Wclippy::try_err",
    "-Wclippy::type_repetition_in_bounds",
    "-Wclippy::unicode_not_nfc",
    "-Wclippy::unnecessary_join",
    "-Wclippy::unnecessary_safety_comment",
    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unnecessary_wraps",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::unreadable_literal",
    "-Wclippy::unseparated_literal_suffix",
    "-Wclippy::unused_async",
    "-Wclippy::unused_peekable",
    "-Wclippy::unused_rounding",
    "-Wclippy::unused_self",
    "-Wclippy::unwrap_in_result",
    "-Wclippy::use_self",
    "-Wclippy::used_underscore_binding",
    "-Wclippy::useless_let_if_seq",
    "-Wclippy::verbose_file_reads",
    "-Wclippy::wildcard_dependencies",
    "-Wclippy::wildcard_imports",
    "-Wclippy::zero_sized_map_values",
]
