[target.'cfg(all())']
rustflags = [
    "-Wclippy::alloc_instead_of_core",
    "-Wclippy::as_conversions",
    "-Wclippy::as_underscore",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::borrow_as_ptr",
    "-Wclippy::branches_sharing_code",
    "-Wclippy::cast_lossless",
    "-Wclippy::cast_possible_truncation",
    "-Wclippy::cast_possible_wrap",
    "-Wclippy::cast_precision_loss",
    "-Wclippy::cast_ptr_alignment",
    "-Wclippy::cast_sign_loss",
    "-Wclippy::checked_conversions",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::cloned_instead_of_copied",
    "-Wclippy::copy_iterator",
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::decimal_literal_representation",
    "-Wclippy::default_numeric_fallback",
    "-Wclippy::default_trait_access",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::doc_link_with_quotes",
    "-Wclippy::doc_markdown",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_line_after_outer_attr",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::enum_glob_use",
    "-Wclippy::equatable_if_let",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::explicit_deref_methods",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::explicit_iter_loop",
    "-Wclippy::fallible_impl_from",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::float_cmp_const",
    "-Wclippy::float_cmp",
    "-Wclippy::fn_to_numeric_cast_any",
    "-Wclippy::format_push_string",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::get_unwrap",
    "-Wclippy::if_not_else",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::implicit_clone",
    "-Wclippy::implicit_saturating_sub",
    "-Wclippy::imprecise_flops",
    "-Wclippy::inconsistent_struct_constructor",
    "-Wclippy::index_refutable_slice",
    "-Wclippy::indexing_slicing",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::items_after_statements",
    "-Wclippy::iter_on_empty_collections",
    "-Wclippy::iter_on_single_items",
    "-Wclippy::iter_with_drain",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_instant_elapsed",
    "-Wclippy::manual_string_new",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_bool",
    "-Wclippy::match_on_vec_items",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::mem_forget",
    "-Wclippy::missing_const_for_fn",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::mut_mut",
    "-Wclippy::mutex_atomic",
    "-Wclippy::mutex_integer",
    "-Wclippy::naive_bytecount",
    "-Wclippy::needless_bitwise_bool",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_for_each",
    "-Wclippy::needless_pass_by_value",
    "-Wclippy::negative_feature_names",
    "-Wclippy::no_effect_underscore_binding",
    "-Wclippy::non_ascii_literal",
    "-Wclippy::option_if_let_else",
    "-Wclippy::option_option",
    "-Wclippy::panic_in_result_fn",
    "-Wclippy::ptr_as_ptr",
    "-Wclippy::range_minus_one",
    "-Wclippy::range_plus_one",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::redundant_closure_for_method_calls",
    "-Wclippy::redundant_else",
    "-Wclippy::redundant_pub_crate",
    "-Wclippy::ref_binding_to_reference",
    "-Wclippy::ref_option_ref",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_name_method",
    "-Wclippy::self_named_module_files",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::similar_names",
    "-Wclippy::single_match_else",
    "-Wclippy::stable_sort_primitive",
    "-Wclippy::std_instead_of_alloc",
    "-Wclippy::std_instead_of_core",
    "-Wclippy::str_to_string",
    "-Wclippy::string_add",
    "-Wclippy::string_lit_as_bytes",
    "-Wclippy::string_to_string",
    "-Wclippy::suboptimal_flops",
    "-Wclippy::suspicious_operation_groupings",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::trivial_regex",
    "-Wclippy::try_err",
    "-Wclippy::type_repetition_in_bounds",
    "-Wclippy::undocumented_unsafe_blocks",
    "-Wclippy::unnecessary_join",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unnecessary_wraps",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::unreadable_literal",
    "-Wclippy::unseparated_literal_suffix",
    "-Wclippy::unused_peekable",
    "-Wclippy::unused_rounding",
    "-Wclippy::unused_self",
    "-Wclippy::unwrap_in_result",
    "-Wclippy::use_self",
    "-Wclippy::used_underscore_binding",
    "-Wclippy::useless_let_if_seq",
    "-Wclippy::wildcard_imports",
]
